name:                mall
version:             0.1.0.0
github:              "githubuser/mall"
license:             
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/mall#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  mall-exe:
    main:                Main.hs
    source-dirs:         app
    # cpp-options: -D_SDL_main_h -DSDL_main_h_
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -optl-mconsole 
    - -optl-mwindows
    # profiling
    # - -prof
    # - -fprof-auto
    # - -fprof-cafs
    # - --enable-library-profiling
    # profiling

    dependencies:
    - mall
    # - gloss
    - sdl2
    - sdl2-image
    - array
    - apecs
    - linear

tests:
  mall-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mall
